import subprocess
import os
import datetime
import html
from cli import command

__author__ = "Sebastian Januchowski"
__category__ = "config.info"
__group__ = "network"
__desc__ = "Full TCP/IP Configuration."

class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    CYAN = '\033[96m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def save_to_html(content, report_path):
    parent_dir = os.path.dirname(report_path)
    if parent_dir and not os.path.exists(parent_dir):
        os.makedirs(parent_dir, exist_ok=True)
    
    report_time = datetime.datetime.now()
    html_template = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Network Audit Report - TERMINAL CLI</title>
    <style>
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            background: linear-gradient(135deg, #0f0f1e 0%, #1a1a2e 100%);
            color: #e0e0e0;
            font-family: 'Segoe UI', 'Consolas', 'Courier New', monospace;
            line-height: 1.6;
            min-height: 100vh;
        }}
        
        .container {{
            max-width: 1000px;
            margin: 0 auto;
            padding: 30px 20px;
        }}
        
        .header-section {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            border-radius: 12px;
            padding: 30px;
            margin-bottom: 30px;
            box-shadow: 0 10px 30px rgba(102, 126, 234, 0.2);
        }}
        
        .header-section h1 {{
            font-size: 2em;
            margin-bottom: 10px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.3);
        }}
        
        .report-time {{
            font-size: 0.95em;
            opacity: 0.95;
            display: flex;
            gap: 20px;
            flex-wrap: wrap;
        }}
        
        .content {{
            background: rgba(255, 255, 255, 0.02);
            border: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 10px;
            padding: 25px;
            backdrop-filter: blur(10px);
            margin-bottom: 30px;
        }}
        
        .adapter {{
            background: linear-gradient(90deg, rgba(59, 142, 234, 0.15) 0%, rgba(59, 142, 234, 0.05) 100%);
            color: #5fbfff;
            font-weight: bold;
            margin: 25px 0 15px 0;
            padding: 12px 15px;
            border-left: 4px solid #5fbfff;
            border-radius: 6px;
            font-size: 1.05em;
        }}
        
        .ip {{
            color: #4ec9b0;
            background: rgba(78, 201, 176, 0.1);
            padding: 2px 6px;
            border-radius: 3px;
            display: inline-block;
        }}
        
        .mac {{
            color: #ce9178;
            background: rgba(206, 145, 120, 0.1);
            padding: 2px 6px;
            border-radius: 3px;
            display: inline-block;
        }}
        
        pre {{
            white-space: pre-wrap;
            word-wrap: break-word;
            background: rgba(0, 0, 0, 0.3);
            padding: 15px;
            border-radius: 8px;
            border-left: 3px solid #667eea;
            overflow-x: auto;
            font-size: 0.95em;
        }}
        
        .footer {{
            text-align: center;
            padding: 20px;
            color: #888;
            font-size: 0.9em;
            border-top: 1px solid rgba(255, 255, 255, 0.1);
            margin-top: 30px;
        }}
        
        .info-row {{
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin-bottom: 15px;
        }}
        
        @media (max-width: 600px) {{
            .info-row {{
                grid-template-columns: 1fr;
            }}
            .header-section h1 {{
                font-size: 1.5em;
            }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header-section">
            <h1>📊 Network Configuration Report</h1>
            <div class="report-time">
                <div>📅 Date: {report_time.strftime('%d.%m.%Y')}</div>
                <div>⏰ Time: {report_time.strftime('%H:%M:%S')}</div>
            </div>
        </div>
        
        <div class="content">
            <pre>{content}</pre>
        </div>
        
        <div class="footer">
            <p>🔧 Report generated by TERMINAL CLI v2026 • Network Analysis System</p>
        </div>
    </div>
</body>
</html>
"""
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(html_template)

@command(name="tcp-ip", aliases=["netcfg", "netconfig"])
def get_full_ipconfig(*args):
    """Full TCP/IP Configuration - displays complete network settings."""
    os.system('') # Activate ANSI in Windows
    report_content = ""
    target_path = os.path.expandvars(r"%userprofile%\.polsoft\psCLI\reports\network_report.html")

    print(f"{Colors.BOLD}{Colors.HEADER}--- Full TCP/IP Configuration (TERMINAL CLI) ---{Colors.ENDC}\n")

    try:
        # Attempt cp852 (Windows PL standard), fallback to utf-8 if needed
        # For English Windows, 'cp437' or 'utf-8' is usually standard
        result = subprocess.run(["ipconfig", "/all"], capture_output=True, text=True, encoding="cp852", shell=True, check=True)
        lines = result.stdout.splitlines()

        for line in lines:
            l_clean = line.strip()
            if not l_clean: 
                report_content += "\n"
                continue
            
            # Safe HTML parsing
            l_safe = html.escape(line)

            if "Karta" in line or "Adapter" in line:
                formatted_cli = f"\n>>> {l_clean}"
                print(f"{Colors.BOLD}{Colors.BLUE}{formatted_cli}{Colors.ENDC}")
                report_content += f'<span class="adapter">{l_safe}</span>'
            elif any(k in line for k in ["IPv4", "Maska", "Subnet", "Brama", "Gateway"]):
                print(f"   {Colors.GREEN}{l_clean}{Colors.ENDC}")
                report_content += f'<span class="ip">{l_safe}</span>\n'
            elif any(k in line for k in ["Physical", "Adres fizyczny", "DHCP", "Lease", "DNS"]):
                print(f"   {Colors.YELLOW}{l_clean}{Colors.ENDC}")
                report_content += f'<span class="mac">{l_safe}</span>\n'
            else:
                print(f"   {l_clean}")
                report_content += f"{l_safe}\n"

        save_to_html(report_content, target_path)
        print(f"\n{Colors.CYAN}[OK] Report saved successfully at:{Colors.ENDC}")
        print(f"{Colors.YELLOW}{target_path}{Colors.ENDC}")

    except subprocess.CalledProcessError:
        print(f"{Colors.RED}[!] Error: Failed to retrieve data from ipconfig.{Colors.ENDC}")
    except Exception as e:
        print(f"{Colors.RED}[!] Critical Error: {e}{Colors.ENDC}")

    finally:
        print("\n" + f"{Colors.BLUE}" + "-"*45 + f"{Colors.ENDC}")
        input("Press Enter to return to TERMINAL CLI...")

if __name__ == "__main__":
    get_full_ipconfig()